import { GoogleGenAI, Modality } from "@google/genai";

const API_KEY = process.env.API_KEY;

if (!API_KEY) {
  throw new Error("API_KEY environment variable is not set");
}

const ai = new GoogleGenAI({ apiKey: API_KEY });

const getFabricPrompt = (fabricType: string): string => {
  switch (fabricType) {
    case 'wool':
      return `The wardrobe should be made of a high-quality Wool fabric. Render its natural sheen and texture, responding realistically to light. Capture the smooth, refined surface of worsted wool, or the thicker, coarser texture of tweed. Emphasize a soft, structured drape. The texture should look tactile and three-dimensional.`;
    case 'cotton':
      return `The wardrobe should be made of a lightweight, breathable Cotton. Show its soft texture and subtle wrinkles that give it a casual yet polished look. Capture the slight sheen and crisp feel of poplin or the subtle diagonal weave of twill. The fabric should look soft and breathable.`;
    case 'linen':
      return `The wardrobe should be made of Linen. Emphasize its lightweight, breathable nature and its naturally textured surface. Render the characteristic wrinkles that give it a relaxed, organic feel. Capture the slight sheen that highlights its raw texture and gives the garment depth.`;
    case 'silk_velvet':
      return `The wardrobe should be luxurious Silk or plush Velvet. If silk, render its smooth, iridescent sheen that catches light in varying ways. If velvet, create a dense, soft texture that creates depth and richness. The fabric must have a natural, elegant flow and a soft, luxurious drape. Use lighting to highlight its sheen and richness.`;
    default:
      return `The clothing must appear highly realistic with photorealistic textures. Pay close attention to the fabric's material, simulating details like the subtle weave of a wool suit, the soft sheen of a silk blouse, or the crispness of high-grade cotton. Ensure the clothing has natural-looking folds, seams, and a realistic drape that corresponds to the subject's posture. The goal is a high-quality, real-world garment, not a flat or artificial rendering.`;
  }
};


export const generateHeadshot = async (
  base64Image: string,
  mimeType: string,
  prompt: string,
  aspectRatio: string,
  wardrobeOption: 'original' | 'generate_new',
  fabricType: string
): Promise<string> => {
  try {
    const fabricInstruction = getFabricPrompt(fabricType);

    const wardrobeInstruction = wardrobeOption === 'original' 
      ? `You MUST keep the exact same clothing and wardrobe as seen in the original selfie. Do not change the color, style, or type of clothing.`
      : `Generate a new, professional wardrobe. ${fabricInstruction}`;

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          {
            inlineData: {
              data: base64Image,
              mimeType: mimeType,
            },
          },
          {
            text: `As an expert AI headshot photographer, your primary goal is to transform a casual selfie into a high-end, professional headshot. The final image must be exceptionally photorealistic and suitable for corporate websites, job applications, and LinkedIn profiles.

**Crucial Instructions:**
1.  **Identity Preservation:** The most critical task is to preserve the person's exact likeness. Use the selfie as a strict reference for their facial features—eye shape, nose, mouth, and unique characteristics must be maintained with high fidelity. The person in the final headshot must be instantly and unmistakably recognizable as the person in the selfie.
2.  **Lighting Independence:** You MUST completely disregard the lighting from the original selfie. The lighting in the final image must be generated *entirely* based on the style prompt below. Do not replicate the original photo's lighting.
3.  **Wardrobe Control:** ${wardrobeInstruction}
4.  **Professionalism:** Apply the user's selected style, but ensure the final result is polished and professional. This includes appropriate lighting, composition, and attire that fits a corporate or business context, unless the style explicitly dictates otherwise.
5.  **Avoid Over-Processing:** Do not over-smooth skin to the point where it looks unnatural. Avoid creating a generic or "stock photo" look. The goal is an authentic, enhanced portrait of the real person.

Apply the following style: "${prompt}".
The final image must have an aspect ratio of approximately ${aspectRatio}.`,
          },
        ],
      },
      config: {
          responseModalities: [Modality.IMAGE],
      },
    });

    for (const part of response.candidates[0].content.parts) {
      if (part.inlineData) {
        return part.inlineData.data;
      }
    }
    
    throw new Error("No image was generated by the API.");

  } catch (error) {
    console.error("Error generating headshot:", error);
    if (error instanceof Error) {
        return Promise.reject(new Error(`Failed to generate headshot: ${error.message}`));
    }
    return Promise.reject(new Error("An unknown error occurred while generating the headshot."));
  }
};